name: pccontour
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - openssl=3.0.14
  - pip=24.0
  - python=3.9.19
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - pip:
      - asttokens==2.4.1
      - attrs==23.2.0
      - blinker==1.8.2
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - flask==3.0.3
      - fonttools==4.53.0
      - idna==3.7
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.0.0
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - parso==0.8.4
      - pillow==10.4.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - prompt-toolkit==3.0.47
      - pure-eval==0.2.2
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pywin32==306
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.18.1
      - scipy==1.13.1
      - six==1.16.0
      - stack-data==0.6.3
      - tenacity==8.4.2
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - zipp==3.19.2
